#include "icewm_config_gen.h"

#include <errno.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#ifdef _WIN32
#include <direct.h>
#elif defined(__APPLE__)
#include <sys/stat.h>
#else
#error "Unsupported platform"
#endif

static int make_dir(const char *path) {
#ifdef _WIN32
    return _mkdir(path) == 0 || errno == EEXIST ? 0 : -1;
#elif defined(__APPLE__)
    return mkdir(path, 0700) == 0 || errno == EEXIST ? 0 : -1;
#else
#error "Unsupported platform"
#endif
}

static int write_if_missing(const char *path, const char *content) {
    FILE *test = fopen(path, "rb");
    FILE *fp = NULL;
    if (test != NULL) {
        (void)fclose(test);
        return 0;
    }
    fp = fopen(path, "wb");
    if (fp == NULL) {
        return -1;
    }
    (void)fputs(content, fp);
    return fclose(fp) == 0 ? 0 : -1;
}

int icewm_config_generate(const char *icewm_dir) {
    char path[1024];
    if (icewm_dir == NULL || icewm_dir[0] == '\0') {
        return -1;
    }
    if (make_dir(icewm_dir) != 0) {
        return -1;
    }
    (void)snprintf(path, sizeof(path), "%s/preferences", icewm_dir);
    if (write_if_missing(path,
                         "# Xile default IceWM preferences - generated by Xile, do not edit manually\n"
                         "TaskBarAtTop=0\nTaskBarShowWorkspaces=1\nTaskBarShowWindows=1\n"
                         "TaskBarShowClock=1\nTaskBarShowCPUStatus=1\n"
                         "TaskBarClockFormat=\"%H:%M  %a %d %b\"\nTaskBarDoubleHeight=0\n"
                         "DesktopBackgroundColor=\"#0d0d0f\"\nDesktopBackgroundImage=\"\"\n"
                         "IconPath=\"/usr/share/pixmaps:/usr/share/icons\"\n"
                         "MenuFont=\"Liberation Sans:size=10\"\nTitleFont=\"Liberation Sans:bold:size=10\"\n"
                         "NormalFont=\"Liberation Sans:size=10\"\nFixedFont=\"Liberation Mono:size=10\"\n"
                         "PeekBehindMouse=0\nFocusModel=1\nWarpPointer=0\nClickToFocus=1\n"
                         "QuickSwitch=1\nQuickSwitchToFocused=1\n") != 0) {
        return -1;
    }
    (void)snprintf(path, sizeof(path), "%s/toolbar", icewm_dir);
    if (write_if_missing(path, "prog Terminal utilities-terminal xterm\nprog Files folder thunar\n") != 0) {
        return -1;
    }
    (void)snprintf(path, sizeof(path), "%s/menu", icewm_dir);
    return write_if_missing(path,
                            "prog Terminal utilities-terminal xterm\n"
                            "prog \"Exit Xile\" system-log-out \"xile-ctl --exit\"\n");
}
